import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { Amplify } from "aws-amplify";

// Import the Amplify configuration
// Note: This file is generated by running 'npx ampx sandbox'
import outputs from "../amplify_outputs.json";

// Configure Amplify
Amplify.configure(outputs);

const isDevelopment = import.meta.env.DEV;

ReactDOM.createRoot(document.getElementById("root")!).render(
  isDevelopment ? (
    <React.StrictMode>
      <App />
    </React.StrictMode>
  ) : (
    <App />
  )
);
