import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { Amplify } from "aws-amplify";

// Import the Amplify configuration
// Note: This file is generated by running 'npx ampx sandbox'
import outputs from "../amplify_outputs.json";

try {
  Amplify.configure(outputs);
  console.log("Amplify configured successfully");
} catch (error) {
  console.error("Amplify configuration error:", error);
  console.warn("You may need to run \"npx ampx sandbox\" to generate amplify_outputs.json");
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
